[workspace]
members = [
    "ferment",
    "ferment-example",
    "ferment-example-entry-point",
    "ferment-example-nested",
    "ferment-example-platform",
    "ferment-example-thread-safe",
    "ferment-example-traits-nested",
    "ferment-example-traits",
    "ferment-interfaces",
    "ferment-macro",
]
resolver = "2"

[workspace.package]
authors = ["Vladimir Pirogov <vladimir.pirogov@dash.org>"]
description = "Procedural macro for FFI and its interfaces & helpers"
homepage = "https://github.com/pankcuf/ferment"
license = "MIT"
keywords = ["ffi", "macro", "c-bindings", "syntax-tree"]

[profile.release]
lto = "thin"
opt-level = 3

