[package]
name = "ferment-interfaces"
version = "0.1.4"
edition = "2021"
license = "MIT"
description = "Traits for FFI conversions and some helper methods"

[dependencies]
indexmap = { version = "2.0.2", features = ["serde"] }

[lib]
name = "ferment_interfaces"
